[Appearance]\ncustom_palette=true\ncolor_scheme_path=/home/vladimir/.local/share/color-schemes/DankMatugen.colors\n
icon_theme=Papirus-Dark
color_scheme_path=/home/vladimir/.local/share/color-schemes/DankMatugen.colors
custom_palette=true
