[main]
# lines=10
icon-theme=Papirus-Dark
dpi-aware=no
font=monospace:size=16
terminal=alacritty -e
anchor=center
[colors]
background=181818ff
text=d8d8d8ff
prompt=b8c0e0ff
placeholder=8087a2ff
input=cad3f5ff
match=90a959ff
selection=6b6b6bff
selection-text=d8d8d8ff
selection-match=aac474ff
counter=8087a2ff
border=aa759fff
[border]
radius=0
width=2
