[preferred]
default=gnome;gtk;kde;wlr;
org.freedesktop.impl.portal.FileChooser=kde;
org.freedesktop.impl.portal.Access=gnome;
org.freedesktop.impl.portal.Secret=gnome-keyring;
org.freedesktop.impl.portal.Screenshot=gnome;
org.freedesktop.impl.portal.ScreenCast=gnome;
